spring:
  data:
    mongodb:
      host: localhost
      database: iuv
      port: 27017
  datasource:
    iuv:
      url: jdbc:mysql://localhost:3306/iuvmoodle
      username: ${IUV_MYSQL_USERNAME}
      password: ${IUV_MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    notification-log:
      url: ${NOTIFICATION_LOG_MYSQL_URL}
      username: ${NOTIFICATION_LOG_MYSQL_USERNAME}
      password: ${NOTIFICATION_LOG_MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: ${MAIL_SERVER_HOST}
    port: ${MAIL_SERVER_PORT}
    username: ${MAIL_SERVER_USERNAME}
    password: ${MAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
  thymeleaf:
    prefix: classpath:/email/template/
    suffix: .html
html-templates:
  teacher:
    course-inactive: "teacher_course_inactivity"
    course-missing-welcome-message: "teacher_course_missing_welcome_message"
    course-activities-pending-grading: "teacher_course_activities_pending_grading"
  student:
    course-inactive: ""
    course-activities-pending-submission: ""
  default: ""