# spring:
#     datasource:
#         url: jdbc:mysql://localhost:3306/your_database_name
#         username: $DATABASE_USERNAME
#         password: $DATABASE_PASSWORD
#         driver-class-name: com.mysql.cj.jdbc.Driver